### ISSUE TITLE
Hi, if I use this into practical application, is that need I use two insta360 cameras to setup the system? thanks a lot.

### ISSUE THREAD

**Issue by semchan** [brownvc/matryodshka#11]

**Comment by cr333** [comment]
I'm afraid using two 360° videos from two separate 360° cameras won't work.

The expected input of our method is a 360° 3D-stitched video (a.k.a. omnidirectional stereo or ODS video), which can for example be captured with an [Insta360 Pro](https://www.insta360.com/us/product/insta360-pro/) camera.
