### ISSUE TITLE
An error when running test.py

### ISSUE THREAD

**Issue by Miawwww** [brownvc/matryodshka#5]
Thanks very much for sharing the code. However, when I try to execute test.py with pre-trained models, I receive an error about checkpoint.

Exception has occurred: InvalidArgumentError
Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,3,256,256] rhs shape= [3,3,257,256]
	 [[node save/Assign_17 (defined at home/tuxiang/Documents/wjy/matryodshka-main/test.py:192) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_17:
 net/conv3_1/weights (defined at home/tuxiang/Documents/wjy/matryodshka-main/matryodshka/nets.py:411)

It would be great if you could provide some insight for solving this issue.

Thank you very much.

**Comment by TanyaStevens** [comment]
Hello,

I have been getting the same error as well. Could you please tell us how you solved the issue? 

Thanks!

**Comment by AnshMittal1811** [comment]
Were you able to solve this issue?
