### ISSUE TITLE
Training MatryODShka on ERP Images

### ISSUE THREAD

**Issue by MarcelRogge** [brownvc/matryodshka#6]
Hello @jamestompkin and @iszihan, I am a student currently working with spherical view synthesis. I would like to be able to make comparisons with MatryODShka but am using ERP images instead of ODS images. Would it be possible to also train MatryODShka with ERP images as input? If not, do you think it would be fair to instead create the 2 sphere volumes using 2 ERP images and projecting each to a location between them?

**Comment by jamestompkin** [comment]
Hi @MarcelRogge, thanks for the question and sorry for the delay.
You can certainly try! 
There are some kinds of camera systems that might capture 2x ERP, using 2x 360 cameras, and it's possible to reproject one into the other (ignoring the self-occluded areas from the 2x 360 cameras). In the paper, we compare to a method (ODSNet - forgive the title) that does inference based on 2x ERP, but using a different technical approach.

Practically, you'd have to use different projection functions for creating the sphere sweeps.

Best wishes,
James

**Comment by MarcelRogge** [comment]
Hello @jamestompkin, thanks for the reply!

Best,
Marcel
